name: Markdown Checks

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup image
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm install
    - run: npm run lint

  spellcheck:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup image
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm install
    - run: npm run spellcheck